### ISSUE TITLE
モーニングスター

### ISSUE THREAD

**Issue by wintermaples** [wintermaples/reversi_tag_planning#2]
右クリック時に体力をハート５個分回復する。
クールダウンは30秒。

**Comment by wintermaples** [comment]
作成完了済み

**Comment by Grave-exeu** [comment]
ナーフ
回復力：♡３個→♡全回復に変更
理由：回復力の割にクールダウンが長いとの声

クールダウン：２５秒→６０秒
理由：回復力の増加とともに大幅な時間調整を加えた。
