### ISSUE TITLE
煙幕

### ISSUE THREAD

**Issue by wintermaples** [wintermaples/reversi_tag_planning#4]
右クリックすると
使用者:

- 透明化: 10秒
- スピードLv2: 2秒 

半径25m以内のキラー:

- 盲目: 5秒

を付与する。
クールダウンは15秒。

**Comment by wintermaples** [comment]
作成完了済み

**Comment by Grave-exeu** [comment]
ナーフ
クールダウン：１５秒→３５秒へ変更

**Comment by Grave-exeu** [comment]
変更内容

バフ
速度上昇Lv2：3秒

ナーフ
弱体化：4秒
透明化：４秒
盲目：２秒
