### ISSUE TITLE
網

### ISSUE THREAD

**Issue by wintermaples** [wintermaples/reversi_tag_planning#5]
右クリックすると自身の位置に罠を仕掛ける。
罠は、半径7m以内に近づいたキラーに以下の効果を付与した後消滅する。

- 鈍足Lv127: 7秒
- ジャンプブーストLv-128: 7秒

クールダウンは60秒。

**Comment by wintermaples** [comment]
作成完了済み

**Comment by Grave-exeu** [comment]
追加：
発光効果:12秒
